name: goreleaser
on:
  release:
    types: [created, published]   # run after release-please makes the release
  workflow_dispatch: {}           # allow manual run for testing

permissions:
  contents: write                 # needed to upload assets

concurrency:
  group: goreleaser-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }   # or your project’s Go version
      - run: go mod download
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}