name: goreleaser
on:
  push:
    tags: ["v*"]          # run when a tag like v0.1.3 is pushed
  release:
    types: [published]    # ALSO run when Release-Please publishes a release

permissions:
  contents: write         # required to upload assets to the release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }
      - run: go mod download
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
